<?php

/**
 * Default system settings.
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    // Artha Business OS branding. Env-driven so upstream merges stay clean and
    // Scalingo can override without a code change. Indigo #202870 / gold #E0B030.
    'app-name'             => env('APP_NAME', 'Artha Docs'),
    'app-logo'             => env('APP_LOGO', '/artha-logo.png'),
    'app-icon'             => env('APP_ICON', '/icon.png'),
    'app-name-header'      => true,
    'app-editor'           => 'wysiwyg',
    'app-color'            => env('APP_COLOR', '#202870'),
    'app-color-light'      => env('APP_COLOR_LIGHT', 'rgba(32,40,112,0.12)'),
    'link-color'           => env('APP_LINK_COLOR', '#202870'),
    'bookshelf-color'      => '#a94747',
    'book-color'           => '#077b70',
    'chapter-color'        => '#af4d0d',
    'page-color'           => '#202870',
    'page-draft-color'     => '#7e50b1',
    'app-color-dark'       => env('APP_COLOR_DARK', '#7782e6'),
    'app-color-light-dark' => env('APP_COLOR_LIGHT_DARK', 'rgba(119,130,230,0.15)'),
    'link-color-dark'      => env('APP_LINK_COLOR_DARK', '#9aa3f0'),
    'bookshelf-color-dark' => '#ff5454',
    'book-color-dark'      => '#389f60',
    'chapter-color-dark'   => '#ee7a2d',
    'page-color-dark'      => '#429fe3',
    'page-draft-color-dark' => '#a66ce8',
    'app-custom-head'      => false,
    'registration-enabled' => false,

    // User-level default settings
    'user' => [
        'ui-shortcuts'          => '{}',
        'ui-shortcuts-enabled'  => false,
        'dark-mode-enabled'     => env('APP_DEFAULT_DARK_MODE', false),
        'bookshelves_view_type' => env('APP_VIEWS_BOOKSHELVES', 'grid'),
        'bookshelf_view_type'   => env('APP_VIEWS_BOOKSHELF', 'grid'),
        'books_view_type'       => env('APP_VIEWS_BOOKS', 'grid'),
        'notifications#comment-mentions' => true,
    ],

];
